const getters = {
  sidebar: (state) => state.app.sidebar,
  size: (state) => state.app.size,
  device: (state) => state.app.device,
  visitedViews: (state) => state.tagsView.visitedViews,
  cachedViews: (state) => state.tagsView.cachedViews,
  token: (state) => state.user.token,
  tenantName: (state) => state.user.tenantName,
  tenantList: (state) => state.user.tenantList,
  avatar: (state) => state.user.avatar,
  name: (state) => state.user.name,
  id: (state) => state.user.id,
  user: (state) => state.user.all,
  introduction: (state) => state.user.introduction,
  roles: (state) => state.user.roles,
  permissions: (state) => state.user.permissions,
  permission_routes: (state) => state.permission.routes,
  topbarRouters: (state) => state.permission.topbarRouters,
  defaultRoutes: (state) => state.permission.defaultRoutes,
  sidebarRouters: (state) => state.permission.sidebarRouters,
  dict: (state) => state.dictionary.dict,
  kvList: (state) => state.dictionary.kvList,
  deviceList: (state) => state.dictionary.deviceList,
  periodtime: (state) => state.video.periodtime,
  backvalue: (state) => state.video.backvalue,
};
export default getters
